name: Comment on the pull request

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["Receive PR"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: pr-number

      - name: 'Download canbench comments'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "canbench_comments"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/canbench_comments.zip', Buffer.from(download.data));
      - run: unzip canbench_comments.zip

      - name: 'Set PR'
        id: set_pr
        run: echo "::set-output name=pr_number::$(cat ./pr-number)"

      - name: 'Read PR'
        run: echo "The number is ${{ steps.set_pr.outputs.pr_number }}"

      - name: Post comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: ./canbench_comment
          comment_tag: test
          pr_number: ${{ steps.set_pr.outputs.pr_number }}

