name: Comment on PR

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: 'hi'
        run: echo "hello"
