name: Receive PR

# read-only repo token
# no access to secrets
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:        
      - uses: actions/checkout@v2

      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR

      - name: Save canbench comments
        run: |
          mkdir -p ./canbench_comments
          echo "# \`canbench\`" > ./canbench_comments/canbench_comment

      - uses: actions/upload-artifact@v4
        with:
          name: pr-number
          path: pr/NR

      - uses: actions/upload-artifact@v4
        with:
          name: canbench_comments
          path: canbench_comments/


